# Generated by Django 4.1.1 on 2022-10-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Локация')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя пользователя до 30 знаков', max_length=60, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию пользователя до 50 знаков', max_length=80, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(help_text='Не менее 8 символов', max_length=30, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('member', 'Пользователь'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='member', max_length=12)),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('location', models.ManyToManyField(to='users.location')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
