# Generated by Django 4.1.1 on 2022-10-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_description_alter_ad_image_and_more'),
        ('users', '0003_alter_location_lat_alter_location_log_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
