# Generated by Django 4.1.1 on 2022-10-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_description_alter_ad_image_and_more'),
        ('users', '0004_rename_user_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='log',
            new_name='lng',
        ),
    ]
