# Generated by Django 4.1.1 on 2022-10-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_location_is_activ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_activ',
        ),
    ]
